language: python
python:
  - "2.6"
  - "2.7"

before_install:
    - pip install pip --upgrade
    - pip install python-coveralls
    - sudo apt-get install python-dev libevent-dev

# command to install dependencies
install: python setup.py install

# command to run tests
script:
- coverage run --source=socketio setup.py test
- coverage report

after_script:
- coveralls
